# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: acksin
provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "*"
      # TODO: This needs to be limited to just the bucket you are using.




# you can overwrite defaults here
defaults:
    stage: dev
    region: us-west-2

# you can add packaging information here
#package:
#    include:
#        - include-me.js
#    exclude:
#        - exclude-me.js
#    artifact: my-service-code.zip

functions:
    mentalmodels:
        handler: handler.handler
        memorySize: 128
        timeout: 300

#       you can add any of the following events
#       events:
#           - http:
#               path: users/create
#               method: get
#           - s3: ${bucket}
#           - schedule: rate(10 minutes)
#           - sns: greeter-topic
